# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := build_lib build_test

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

build_lib: 
	@echo "==== Building build_lib ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f build_lib.make

build_test: 
	@echo "==== Building build_test ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f build_test.make

clean:
	@${MAKE} --no-print-directory -C . -f build_lib.make clean
	@${MAKE} --no-print-directory -C . -f build_test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo "   debug32"
	@echo "   release32"
	@echo "   debug64"
	@echo "   release64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   build_lib"
	@echo "   build_test"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
